### ISSUE TITLE
Image (sif) upload fails with ImageNameIllegalException

### ISSUE THREAD

**Issue by dstrbad** [CloudiFacturing/clfpy#7]
Hi,

I'm trying to upload `sif` Singularity image using `cflpy` but getting `ImageNameIllegalException`. 

I am aware that all (or at least ones I've seen) of your examples cover `simg` case but Singularity documentation states:
>compressed read-only Singularity Image File (SIF) format suitable for production (default)
>By default the container will be converted to a compressed, read-only SIF

I've looked into `sh` build scripts under `code-examples` and Singularity documentation and not sure if just extension name changed or there are really differences between `simg` and `sif` images. 

Should your backend support and accept `sif` files without returning exception? Am I missing something?

Thanks in advance.

Kind regards
Dejan

**Comment by rojsc** [comment]
Hi Dejan,

Please try to simply change the extension of your image to `.simg`. (The name checking was implemented before Singularity version 3.0 introduced the `.sif` extension.) It shouldn't make any difference for the execution.

Best regards,
Robert

**Comment by dstrbad** [comment]
Hi Robert, 

yes that works, I can confirm that.

Just wanted to make sure I'm not missing anything else.

Thanks


Kind regards
Dejan

**Comment by rojsc** [comment]
Ok, then it's just a not-so-critical piece of technical debt on the SemWES side. ;) Thanks for reaching out in any way!
